version: '3.8'

services:
  nginx:
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - 8080:80
    restart: always
    depends_on:
      - "app"
      - "api"

  app:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    volumes:
      - ./frontend/:/usr/src/app
    restart: on-failure

  api:
    build:
      context: ./server/
      dockerfile: Dockerfile
    volumes:
      - ./server:/usr/src/app
    env_file:
      - ./server/.env
    restart: on-failure