version: '3.8'

services:
  nginx:
    image: fogre/bloglist-nginx
    ports:
      - 8080:80
    restart: always
    depends_on:
      - "app"
      - "api"

  app:
    image: fogre/bloglist-app
    restart: on-failure

  api:
    image: fogre/bloglist-api
    restart: on-failure
    environment:
      - DATABASE_URL=wellthiswasjustfortestingsoItdidntmatteranyways
      - REDIS_URL=redis://redis_blogapi:6379/
    depends_on:
      redis:
        condition: service_started

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    command: ['redis-server']
    container_name: redis_blogapi
    restart: on-failure
