name: Backend CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

defaults:
  run:
    working-directory: ./server


jobs:
  backend-test:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        # Set health checks
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

      postgres:
        image: postgres
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: blogapitest
        # Set health checks
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Run lint
        run: npm run lint:fix

      - name: Create test .env file
        run: |
          touch .env
          echo TEST_DATABASE_URL="postgres://root:postgres@localhost:5432/blogapitest" >> .env
          echo REDIS_URL="redis://localhost:6379/" >> .env
          echo SECRET=sekret12346 >> .env
          cat .env
          echo "$PWD"

      - name: Run tests
        run: npm run test

