name: Backend CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

defaults:
  run:
    working-directory: ./server


jobs:
  runner-job:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        # Set health checks
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: blogapi
        # Set health checks
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Run lint
        run: npm run lint:fix

      - name: Run tests
        run: npm run test
        env:
          TEST_DATABASE_URL: postgres://postgres:postgres@localhost:5432/blogapi
          REDIS_URL: redis://localhost:6379/
          SECRET: sekret123456
